### ISSUE TITLE
Error at line 1

### ISSUE THREAD

**Issue by sergei-lobanov** [phonowell/genshin-impact-script#10]
Hi, not able to open your script due to an error in line 1:
Line text <!DOCTYPE HTML... 
Error the line doesn't contain a recognized action

**Comment by phonowell** [comment]
It looks like you weren't able to download the correct file, try this link
[https://raw.githubusercontent.com/phonowell/genshin-impact-script/master/source/index.ahk](url)

**Comment by Rubaka** [comment]
@phonowell thanks you, this one works well. the issue can be closed. 
Please update the link in the readme file, as right now the link is: https://github.com/phonowell/genshin-impact-script/blob/master/source/index.ahk and this file isn't working

**Comment by phonowell** [comment]
got it ;)
