### ISSUE TITLE
Error: "Target is required" on GIS 0.0.35

### ISSUE THREAD

**Issue by Qulox** [phonowell/genshin-impact-script#101]
When opening GIS.exe this appears:
![image](https://user-images.githubusercontent.com/15495523/167065373-2a758676-d4c2-483d-aee2-967f1c302ce8.png)

The game opens normally and GIS loads in system tray but doesn't do anything in game. 

My PC is running Win11 at 1080p, my config.ini:

`[basic]
; 游戏路径
; 例如：C:\Genshin Impact\Genshin Impact Game\YuanShen.exe
; Game path
; e.g., C:\Genshin Impact\Genshin Impact Game\GenshinImpact.exe
path = C:\Games\Genshin Impact\Genshin Impact Game\GenshinImpact.exe

[better jump]
enable = 1

[better pickup]
enable = 1
use-fast-pickup = 1
use-quick-skip = 1

[skill timer]
enable = 1

[sound]
use-beep = 1
use-mute-when-idle = 0`

**Comment by PotatoDestroyer** [comment]
Same here. 
Tried running with Administrator. No luck and im kinda too dumb to fix. 
MASTER, PLS HELP <3

![image](https://user-images.githubusercontent.com/47395819/167067061-f9a931a6-ea6e-41be-a42d-3579ca33e5bf.png)

![image](https://user-images.githubusercontent.com/47395819/167067570-4c04c18c-59e6-4139-864d-29fe48f26a71.png)

**Comment by Kuannz** [comment]
You need to add this line below "Path"

process = GenshinImpact.exe

**Comment by Qulox** [comment]
Thanks. Now is working.

**Comment by phonowell** [comment]
This is indeed a bug and will be fixed later
