### ISSUE TITLE
auto pick-up not working and no skill timer 

### ISSUE THREAD

**Issue by nalhiff** [phonowell/genshin-impact-script#104]
first of all, thank you very much for your hard work.. i really appreciate the thing that you do for us!

after upgrading to v0.0.35, i am unable to use the auto pick up feature and the auto pick-up was enabled by using Alt + F shortcut
already press F12 to recognize the team so i'm able to use the skill timer, but i cant found the timer

here's my genshin settings
![image](https://user-images.githubusercontent.com/36839431/167852523-0261dcb8-f36f-4410-89ec-ad55d6f75df0.png)

here's the config settings
![image](https://user-images.githubusercontent.com/36839431/167853903-8009c993-1236-486b-bdb4-e9d544b1a71d.png)

using the 0.0.34 just works fine.

**Comment by mmn6d6d6e** [comment]
Does an error message `Error: $.wait: target is required` show up after you run the script?

If so, then it's the same as https://github.com/phonowell/genshin-impact-script/issues/101#issuecomment-1120489230

Check that issue, there is a temporary solution for now.
The permanent fix might be on the future version.

**Comment by BelugaRex** [comment]
我的情况和这个老哥一样，我没有出现错误信息，试过增加那个process，还是不起作用。

**Comment by nalhiff** [comment]
> 

nope, its running perfectly fine.. but the features doesnt working as intended.
i already read that one and phono already commit #101 it 3 days ago if im not wrong


> 我的情况和这个老哥一样，我没有出现错误信息，试过增加那个process，还是不起作用。

您可以重新下载文件，phonowell 已经对其进行了更新以解决该问题。
我正在使用谷歌翻译，请原谅我的中文不好

**Comment by phonowell** [comment]
yes, download v35 again to fix this issue
the section name of the configuration item is wrongly filled

**Comment by nalhiff** [comment]
thank you!, its working as intended now..

**Comment by jasonliaotw** [comment]
Skill timer still not work....

**Comment by phonowell** [comment]
> Skill timer still not work....

lets take a look at your config.ini

**Comment by jasonliaotw** [comment]
> > Skill timer still not work....
> 
> lets take a look at your config.ini

[basic]
; path =

[better jump]
enable = 0

[better pickup]
enable = 1
use-fast-pickup = 1
use-quick-skip = 1

[skill timer]
enable = 1

[sound]
use-beep = 1
use-mute-when-idle = 1
[better-pickup]
enable= 1

**Comment by phonowell** [comment]
> > > Skill timer still not work....
> > 
> > 
> > lets take a look at your config.ini
> 
> [basic] ; path =
> 
> [better jump] enable = 0
> 
> [better pickup] enable = 1 use-fast-pickup = 1 use-quick-skip = 1
> 
> [skill timer] enable = 1
> 
> [sound] use-beep = 1 use-mute-when-idle = 1 [better-pickup] enable= 1

replace the section names like `[better jump]` to `[better-jump]` and have another go

**Comment by jasonliaotw** [comment]
resolve...

new config as below.
`[basic]
; 游戏路径
; 例如：C:\Genshin Impact\Genshin Impact Game\YuanShen.exe
; Game path
; e.g., C:\Genshin Impact\Genshin Impact Game\GenshinImpact.exe
path = "C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact.exe"

[better-jump]
enable = 0

[better-pickup]
enable = 0
use-fast-pickup = 1
use-quick-skip = 1

[skill-timer]
enable = 1

[sound]
use-beep = 1
use-mute-when-idle = 1`
