### ISSUE TITLE
请问操作录制里是怎么监听视角转换的

### ISSUE THREAD

**Issue by org-org-org** [phonowell/genshin-impact-script#109]
我自己写了一个类似按键精灵的脚本，但是没法通过鼠标位置监听视角的变换。目前我想转视角只能按鼠标中键让他自动调整。。。

**Comment by phonowell** [comment]
操作录制里也不能记录视角转换
鼠标太灵活了，按毫秒记录数据量级太大了

**Comment by org-org-org** [comment]
哦哦这样啊，我现在用小键盘代替视角切换。。。虽然很不方便但是勉强能用[笑哭]
