### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by hinyb** [phonowell/genshin-impact-script#11]
就是那个我发现更新之后，我按住F大小写会一直跳，有时候松开F后按ALT会一直切换跑和走，再按一次F才能好（；´д｀）ゞ

**Comment by phonowell** [comment]
按住F时还会执行一次滚轮向下滚动的操作
你是否有在这个动作上绑定别的鼠标宏之类的东西？

**Comment by hinyb** [comment]
没有我只有侧键有个宏

**Comment by hinyb** [comment]
QWQ

**Comment by phonowell** [comment]
那这个问题有点奇怪，回头加个群呗

**Comment by hinyb** [comment]
ok

**Comment by hinyb** [comment]
群的验证消息是啥QWQ

**Comment by phonowell** [comment]
> 群的验证消息是啥QWQ

不记得有设置过这个
你再加一次看看？

**Comment by hinyb** [comment]
是这个吗
coffee-ahk

**Comment by phonowell** [comment]
> 是这个吗
> coffee-ahk

现在改成回答问题了

**Comment by hinyb** [comment]
QWQ还是进不去
