### ISSUE TITLE
tactic吞指令问题&烟绯自用配置（timing版

### ISSUE THREAD

**Issue by yoplk** [phonowell/genshin-impact-script#111]
因为我自己使用的时候发现，时间间隔没设置好就会卡掉某些指令无法执行，而且脚本每次循环的执行速度都不太一样，第二次循环会明显加快速度（也可能是我电脑问题）
*作为烟绯厨，这个问题在烟绯小可爱使用时非常明显，经常吞掉普攻
以下是我自用的版本，第二第三次普攻之间的时间间隔如果调到500以下就会不时吞普攻了，很难受
```
[yanfei]
on-long-press = @e?,100,e,300,a~,300; !@e?,100, a,500,a,500,a,300,a~,300
on-switch = e,300,a~
```
*是的我作为烟绯厨烟绯没满命，只叠三层被动

**Comment by jasonliaotw** [comment]
我有在用烟绯，所以提供一下解法
烟绯在3次普通攻击后，会延长 重击硬直时间(也就是0/1次普攻跟 3次普攻硬直时间不同)，所以我的配置如下

[yanfei]
on-long-press = @e?,e,600,a,50,a~,1050; a,130,a,!@m,130,a,50,a~,1350; a~,1050;
(等待时间依照个人电脑配置会有所不同，自行再修改)

另满命烟绯，可以叠4次普攻的重击加乘，目前只能等待大佬支持 "走A" 的攻击
目前 "走A" 也可以另外支持 心海大招的 补血最大化 

小弟也提供 走A 的作法，就是 tactic 源码段上，支持可以对应 "w" 动作

[sangonomiya_kokomi]
on-long-press = @e?,a,e,1000; a,10,a,!@m,350,w; 210,a,360,s,210

**Comment by phonowell** [comment]
下个版本会更新tactic，用来支持类似的功能
到时候在tactic中使用`\w`这种语法即可触发对应按键
