### ISSUE TITLE
关于自动技能和CD显示的问题

### ISSUE THREAD

**Issue by qq2813798515** [phonowell/genshin-impact-script#12]
是不是宽屏识别不到角色？2560x1080的屏幕全屏情况下计时器没效果
另外自动切人放技能也没效果，即使设置里自定义了相关角色也一样。

**Comment by qq2813798515** [comment]
另外切到副屏以后似乎能正常识别到了，但是为什么会把行秋识别成班尼特

**Comment by qq2813798515** [comment]
还有就是没有写进自定义的角色切换以后是不会自动放技能的，但是倒计时还是会进入CD

**Comment by phonowell** [comment]
- 目前仅支持了16比9的分辨率
- 队伍识别的时候如果识别错误，晃一下视角再试试
- 另外放技能的时候目前并不会校验技能是否真的放成功，所以有可能出现技能没放成功但计时器开始走的情况；这个处理起来比较麻烦，未来会考虑解决一下
