### ISSUE TITLE
character.ini里的指令格式填写错误会导致脚本退出

### ISSUE THREAD

**Issue by shiwangyan** [phonowell/genshin-impact-script#121]
能改成错误指令无效，而不是让脚本退出就好了
最好能改成修改后就能直接测试，而不是要重新加载脚本

**Comment by phonowell** [comment]
v38版本起，可以通过按下`F12`重新加载`character.ini`
此外，能否提供导致跳出的错误指令，用于修复脚本退出问题

**Comment by shiwangyan** [comment]
当时把指令给删了，我也忘了当时写的什么指令了
我刚才又试着写了错误的指令，没遇到脚本退出的情况
那这个问题先不管了吧

**Comment by phonowell** [comment]
好，之后遇到问题的时候再反馈，或者reopen这个issue都可以
