### ISSUE TITLE
识别错误的小问题

### ISSUE THREAD

**Issue by shiwangyan** [phonowell/genshin-impact-script#125]
这种情况下鼠标会去按红色圆圈里的白色部分，弓是西风猎弓
![QQ截图20220813233211](https://user-images.githubusercontent.com/60057517/184500926-6785bdbd-7860-4f06-b9d0-2a1d63cde05f.png)

**Comment by phonowell** [comment]
目前尚未有特别的解决方案，建议转个视角

**Comment by phonowell** [comment]
目前尚未有特别的解决方案，建议转个视角
