### ISSUE TITLE
钓鱼问题

### ISSUE THREAD

**Issue by shiwangyan** [phonowell/genshin-impact-script#129]
不在钓鱼点按F11，这个框会一直跳出来
虽然可以通过点一下游戏，再按F11关掉钓鱼来解决
![image](https://user-images.githubusercontent.com/60057517/187085622-d0888c4a-f326-451a-b508-e1511a1c4459.png)

**Comment by shiwangyan** [comment]
还有，希望能把钓鱼换个快捷键，比如F10之类的

**Comment by phonowell** [comment]
钓鱼模式报错的问题已修复，随v39更新
