### ISSUE TITLE
A suggestion.

### ISSUE THREAD

**Issue by satancurls** [phonowell/genshin-impact-script#13]
Hi, I really appreciate your work.
I found it amazing what you were able to do with AHK, I'm using it and really enjoying it. (:
Could you make an attack mode for Hu Tao?

**Comment by phonowell** [comment]
Glad you like it
We have got a significant problem about the attack mode of Hu Tao: I don't have her
But the good news is that there is an action recording feature in the new version. You can record your actions and send them to me so I can add it in a later version

**Comment by satancurls** [comment]
[replay.txt](https://github.com/phonowell/genshin-impact-script/files/6105582/replay.txt)
Hm... Thanks for your attention! (:
I recorded it and I think this way is ok, I put the E skill command before the combo too....

**Comment by satancurls** [comment]
Hey! I made a better combo. It is the perfect combo for Hu Tao without constellations and using E for a higher DPS.
[replay.txt](https://github.com/phonowell/genshin-impact-script/files/6111048/replay.txt)

**It is called N1CJ:
1 normal attack
1 charged attack
1 jump to cancel the animation**

**Comment by phonowell** [comment]
Thank you for help!
I will add it in next version.
Wish I could get Hu Tao this week.

**Comment by satancurls** [comment]
I saw that you released the update!
I tested it and Hu Tao is working properly but I think Xiangling is having some problem, not sure.
Could it be my ms? 115~150
There is no server in my region yet...

**I uploaded some gifs to show how they look here (:**
🌍 **https://imgur.com/a/uLZiH7l**

**Comment by satancurls** [comment]
Yo. I saw that you updated it, and again I say that I appreciate your work very much 🤧
Hu Tao is working properly for me, it's good! But I think the Xiangling is not working well, I think maybe it's my ms **(120~150)**

**I posted two gifs to show how it's working :)
https://imgur.com/a/NLEQo00**

**Comment by phonowell** [comment]
This is because Xiangling's logic is different from Hu Tao's.

For Hu Tao, the logic is to use charged attack & jumping  cycle after using E.

And for Xiangling, it is using continuous normal attack all the time.

The reason for this is that in most teams, Xiangling's normal attack only takes a very little part of damage.

**Comment by thu2468** [comment]
N1CD for Hu Tao when u got C1 for her.
