### ISSUE TITLE
38和39版本出现莫名奇妙的F键失效问题

### ISSUE THREAD

**Issue by shiwangyan** [phonowell/genshin-impact-script#130]
使用1920 * 1080 窗口模式玩
跟出现问题的场景是跟NPC对话无法选择选项
换成v37就没有问题了

**Comment by phonowell** [comment]
目前未有其他人反馈类似问题，待观察

**Comment by phonowell** [comment]
> > 目前未有其他人反馈类似问题，待观察
> 
> 目前我测试的结果是，在 `better-pickup/enable = 0` 的情况下，点按 `F` 选择选项会出现失效，点按失效时只要长按 `F` 就好了，可能大多数人没有把better-pickup设为0，没有用手动，所以没出现问题。 我猜测是因为修复 `F` 键双击的问题导致的新的bug

并没有能复现

**Comment by shiwangyan** [comment]
> > > 目前未有其他人反馈类似问题，待观察
> > 
> > 
> > 目前我测试的结果是，在 `better-pickup/enable = 0` 的情况下，点按 `F` 选择选项会出现失效，点按失效时只要长按 `F` 就好了，可能大多数人没有把better-pickup设为0，没有用手动，所以没出现问题。 我猜测是因为修复 `F` 键双击的问题导致的新的bug
> 
> 并没有能复现

在这个界面点按 `F` 试试呢？关闭自动对话
![image](https://user-images.githubusercontent.com/60057517/189185454-25480cf4-6617-4eea-8f43-f19537eaa3f6.png)

**Comment by shiwangyan** [comment]
我感觉应该是按 `F` 键到脚本检测按了 `F` 键的时间太长，或者是脚本检测选项图标需要的时间太长导致的
