### ISSUE TITLE
自訂 F12 人物

### ISSUE THREAD

**Issue by seriaati** [phonowell/genshin-impact-script#132]
這個之前提過了，辨識功能不是很準確，或是不太穩定
希望能夠自訂角色
我有看到 characters.ini，但是不太清楚怎麼設定

**Comment by phonowell** [comment]
未发现其他辨识不准确问题
提供一下你的系统版本、游戏运行分辨率、是否窗口化、是否使用任何滤镜
以及识别不准确时的小队成员名单（包含顺序）

**Comment by seriaati** [comment]
系統版本：Windows 11
分辨率：1600x900
窗口化：無
濾鏡：降藍光（Night Light mode)
小隊名單：霄宮，夜闌，鍾離，早柚

另外想順便回報的是，快速跳過劇情以及自動拾取也沒有正常運作

**Comment by phonowell** [comment]
https://github.com/phonowell/genshin-impact-script/blob/master/doc/note.md

第一条就是**不支持任何画面滤镜**

关掉滤镜再试试看吧

**Comment by seriaati** [comment]
我沒有開濾鏡的話眼睛會有點難受
請問可以自訂角色嗎

**Comment by seriaati** [comment]
我關掉濾鏡後仍然無法，但是換成視窗模式就可以了

**Comment by seriaati** [comment]
目前是這樣的：有開濾鏡，開 1660x900，用 alt+enter 關閉全螢幕模式，所有功能可以正常運作

**Comment by phonowell** [comment]
目前暂未有自订角色的计划
