### ISSUE TITLE
按飘号键~是什么功能

### ISSUE THREAD

**Issue by infstellar** [phonowell/genshin-impact-script#134]
翻了几遍文档没有看到，好像是自动战斗？

**Comment by phonowell** [comment]
> 

v41版本测试性添加的功能，v42版本已经移除了

**Comment by infstellar** [comment]
> > 
> 
> v41版本测试性添加的功能，v42版本已经移除了

感觉不错啊，为啥要移除

**Comment by phonowell** [comment]
> > > 
> > 
> > 
> > v41版本测试性添加的功能，v42版本已经移除了
> 
> 感觉不错啊，为啥要移除

不符合预期效果

**Comment by infstellar** [comment]
> > > > 
> > > 
> > > 
> > > v41版本测试性添加的功能，v42版本已经移除了
> > 
> > 
> > 感觉不错啊，为啥要移除
> 
> 不符合预期效果

我自己改了一下，效果还可以，我发群吧

**Comment by infstellar** [comment]
![image](https://user-images.githubusercontent.com/98541813/189641125-5a1eb092-b730-44ec-9076-458158b72ab0.png)
![image](https://user-images.githubusercontent.com/98541813/189641171-f9f40317-f26f-4c3a-ba0f-a17d923a3b63.png)
适配宵宫的时候我加了4行代码
宵宫的输出手法是e, ~@e, a; @e?, e
