### ISSUE TITLE
Tignari doesn't show on the 0.0.42

### ISSUE THREAD

**Issue by jainprashul** [phonowell/genshin-impact-script#135]
![image](https://user-images.githubusercontent.com/20634589/189750641-eb016e69-ce15-4132-998c-487ecba8e746.png)

**Comment by phonowell** [comment]
看起来是因为分辨率所导致的
试试看1600*900分辨率下能否正常工作
这个问题将在下个版本中修复

**Comment by phonowell** [comment]
I was not able to reproduce the problem
From the screenshot, it looks like you have the screen filter on, try turning it off
