### ISSUE TITLE
自动填写地址导致的新bug

### ISSUE THREAD

**Issue by dextersa** [phonowell/genshin-impact-script#136]
新的程序逻辑导致了一个新特性。

我的情况是，在两台游戏路径不同的机器上经常交替执行配置文件同步过的gis.exe。

以前的版本，即便path 参数错误，我在路径错误的机器上只要先启动游戏，后启动gis就不会弹出下面的错误。
现在只要换机器就会报这个错误，并导致脚本停止运行。
因为gis每次都会想办法更新该地址。
我只能每次去修改配置文件清空path或者改为正确的路径。

Error:  Failed attempt to launch program or document:
Action: <d:\stk\genshin impact\genshin impact game\yuanshen.exe>
Params: <>

Specifically: 系统找不到指定的文件。

	Line#
--->	637: Run,source

The current thread will exit.

能否恢复到之前的状态，将检测进程的命令放到这个逻辑前面？
又或者是，当发现地址错误的时候让程序进入等待状态，直到检测到游戏进程？

**Comment by phonowell** [comment]
两台机器各用一份gis就可以了

**Comment by dextersa** [comment]
已经把gis分开用了。
我提交的issues想表达是，原来地址其实不是一个必须参数。
但新逻辑意味着配置文件里的游戏地址一旦错误脚本就无法运行了？
所以难道是为了防止更多的被盗用故意修改成这样的？

**Comment by phonowell** [comment]
很有道理，下个版本中解决这个问题

**Comment by dextersa** [comment]
额，看来我是一个不会描述issues的人，一开始我就应该说第二段的内容而不是前面那么多废话。
下次改进。

**Comment by phonowell** [comment]
已经改好，会在v42版本中更新
issue先关了
