### ISSUE TITLE
The Script doesn't work

### ISSUE THREAD

**Issue by PradMAc** [phonowell/genshin-impact-script#138]
hello, 
im here after a hard working of trying to launch the script
i'm windows user and i have checked that my path = Genshinimpact.exe and everything is just right but in the game, like when i try it, nothing work, i can't see Timer for cooldown or other features, the only thing that is working that i put the recommended hu tao code in config.ini and also it's not working fully, when i press the 4th and 5th mouse button it just give me a charged attack nothing else + when i press F12 it comes a sound so i don't know whats happened

**Comment by phonowell** [comment]
First, you need to make sure you are not using any graphics filters
Scripts work on image recognition, and graphics filters will break that

Also, the character settings are now placed in a separate `character.ini` file
and the mouse side buttons need to be configured via the additional items `on-side-button-1` and `on-side-button-2`.

Finally, if you are still experiencing problems
plz continue to give feedback

**Comment by PradMAc** [comment]
im not using game filters and i tried to put hutao recommended N1JC but when i click on onside button 1 or 2 it just do a charged attack without jump or cancel so im sure that im not using game filters, and everything is just fine but it's not working for me, do i have to download some required software to make it work successfuly? and please explain more about configure the side buttons im using Glorious Model O.

**Comment by PotatoDestroyer** [comment]
I made a video, hope it helps

https://www.youtube.com/watch?v=foxdLtU6Hc4

**Comment by PradMAc** [comment]
note : i've reinstalled the game to make sure that i dont have game filters. 

https://youtu.be/JwwoYCYVpg0

**Comment by PradMAc** [comment]
and im clicking F12 to scan the team but nothing works

**Comment by PradMAc** [comment]
i did everything, nothing works unfortunately, idk what to do, im pretty sure that i did the same steps but it's not showing anything

**Comment by PotatoDestroyer** [comment]
A video would be nice

**Comment by PradMAc** [comment]
i'll reinstall my windows and check it and i'll inform u
