### ISSUE TITLE
人物识别bug和一个建议

### ISSUE THREAD

**Issue by 5night** [phonowell/genshin-impact-script#14]
bug，会把行秋识别为班尼特，cd时间错误显示为5秒。
建议：
按一下鼠标右键或者某个键盘按键切换自动跑步（而非长按右键）感觉更省劲T_T

**Comment by phonowell** [comment]
- 行秋错认为班尼特是否稳定复现？
- 首先，该功能实现完全可行；但其不能被分配给鼠标右键，这会导致在真正需要使用闪避时无法操作；但分配给其他按键，又存在和未来某个功能按键冲突的可能性……

**Comment by 5night** [comment]
试了一下又好了orz

**Comment by phonowell** [comment]
> 试了一下又好了orz

人物识别依靠取色的，当时应该是背景色中有类色班尼特头发颜色的物体
通常来说遇到这种问题的时候，视角转一下再重新取一下就好了
