### ISSUE TITLE
Small stutters with the script on

### ISSUE THREAD

**Issue by fractalmoth** [phonowell/genshin-impact-script#141]
Hi. Ever since 3.1 the game will give micro stutters when I have the script turned on. When I turn it off the stutters go away. I've been using the script for months and never had this problem before this patch. Happens using 0.42 and 0.43 versions.

**Comment by phonowell** [comment]
Hey there! Thanks for the heads up about the stuttering issue with the script. I'll definitely take a look and see what's going on. In the meantime, could you give me a little more info about what's happening? Any extra details would be really helpful in getting to the bottom of this. Thanks again for letting me know!
