### ISSUE TITLE
闪避按键失效问题

### ISSUE THREAD

**Issue by yoplk** [phonowell/genshin-impact-script#143]
在战斗之后（或战斗中）偶尔出现闪避按键失效的问题，左shift按键与鼠标右键均无反应，在设置中更改冲刺键位后，新键位也不能触发冲刺，关闭GIS恢复正常

**Comment by phonowell** [comment]
走跑切换按键设置的是什么？

**Comment by yoplk** [comment]
> 

按照说明改的右control

**Comment by phonowell** [comment]
最近代码重构，改动非常多
这个问题可能要留待v44发布后，看新版本是否能重现之后再进行排错了

**Comment by yoplk** [comment]
还没找到复现的方法，但是发现按alt+shift就可以恢复正常，可能是自动跑步的问题
