### ISSUE TITLE
ERROR 8121 invalid function  token

### ISSUE THREAD

**Issue by yuanch1** [phonowell/genshin-impact-script#146]
![image](https://user-images.githubusercontent.com/52809871/198835238-fe8ea6a0-7377-45db-89be-e2818099a06c.png)
不太明白是怎么回事，求大佬看看

**Comment by GaneshArwans** [comment]
Me too...

**Comment by phonowell** [comment]
该问题仅在使用汉语的新用户中出现，已在v45中修复
更新即可解决
