### ISSUE TITLE
bug两则+疑似bug一则

### ISSUE THREAD

**Issue by 5night** [phonowell/genshin-impact-script#15]
1.在按住右键激活跑步后，同时按下SHIFT+A键（此时不要松开右键）（SHIFT键稍微按早一点点成功率会更高），人物会一直向左跑，松开右键也无法解除。解除方法：再次按下SHIFT+A键。（要是能不按键向前跑就是特性了orz）
终于稳定复现了这个bug，真不容易。

2.刚开脚本时，F12无效，感觉没有开始识别，解决方法：按一次CTRL+F5后，再按f12才能生效，原因不明。

3.按v会打开地图，和原本的快捷键（v键跟踪任务方向）冲突了，疑似bug。

**Comment by 5night** [comment]
P.S. 胡桃的E状态开启时长按鼠标左键挺好用的，不过E状态关闭时在攻击时按任何一个方向键都会导致起跳，导致基本没法用，是策略设置如此么？
P.P.S. 胡桃可以在试用活动中测试，不过我的建议是没有的人物倒是可以不做，各方面都比较困难。

**Comment by 5night** [comment]
好家伙，我发现coffee-ahk就是大佬你写的还行。。。 这两个我都是半吊子，自己改的话有点难orz

**Comment by phonowell** [comment]
- 冲刺时shift+a这个问题我没能复现，能否录制一个动作给我瞅瞅
- f12这个问题倒是一直有，不过之前觉得也没啥大问题就没去解决……下个版本修复
- v后接m是我的设置，因为老是先v一下马上接m有点烦，没想到会造成困扰；下个版本改掉
- 胡桃那个平A加方向就跳是策略设置，目前看起来是有些过激了；下个版本改掉
- 胡桃不出我也很为难，真的很为难 QAQ

**Comment by phonowell** [comment]
已更新

**Comment by 5night** [comment]
F12、v键和胡桃的问题都修复了，赞一下。
尝试录制了一下，发现replay里面没有记录到任何操作。
另外发现不按右键，SHIFT+A键可以直接触发，似乎输入是一个大写字母A，无论中英文输入法都可以触发。
录制了一个实际效果，如下。

[https://imgur.com/XYRDvHU](url)

**Comment by phonowell** [comment]
放图的时候不要带上uid
`shift`这个键脚本并没有捕获做处理，我估计可能是这方面的原因

**Comment by 5night** [comment]
好的

**Comment by 5night** [comment]
分享一些我自用的设置：
自动开宝箱捡东西，屏蔽掉对话和烹饪
T键打开队伍配置
page down一键关闭声音
1键:选择倒数第二个对话选项
2键:选择最后一个对话选项
[：装备道具
]：升级道具
ESC：退出七天神像
P：跳过对话（出选项前一直点空格）

**Comment by phonowell** [comment]
嗯……pageDown一键关闭声音这个是如何做的？

**Comment by 5night** [comment]
有点标题党了，就是模拟鼠标点击O(∩_∩)O~

**Comment by phonowell** [comment]
> 有点标题党了，就是模拟鼠标点击O(∩_∩)O~

那这个操作链路有点长了
我倒是想弄个窗口非活动时关闭声音，然而没找到简单易行的方法……

**Comment by jasonliaotw** [comment]
> 分享一些我自用的设置：
> 自动开宝箱捡东西，屏蔽掉对话和烹饪
> T键打开队伍配置
> page down一键关闭声音
> 1键:选择倒数第二个对话选项
> 2键:选择最后一个对话选项
> [：装备道具
> ]：升级道具
> ESC：退出七天神像
> P：跳过对话（出选项前一直点空格）

可以分享吗?

**Comment by 5night** [comment]
> > 分享一些我自用的设置：
> > 自动开宝箱捡东西，屏蔽掉对话和烹饪
> > T键打开队伍配置
> > page down一键关闭声音
> > 1键:选择倒数第二个对话选项
> > 2键:选择最后一个对话选项
> > [：装备道具
> > ]：升级道具
> > ESC：退出七天神像
> > P：跳过对话（出选项前一直点空格）
> 
> 可以分享吗?

只对我的屏幕分辨率失效，换个电脑相当于要重写
