### ISSUE TITLE
连按闪避与方向键不正常行走

### ISSUE THREAD

**Issue by Ice-wilderness** [phonowell/genshin-impact-script#151]
在快速按下shift+w/a/s/d两次的情况下，会出现一直朝着按下的方向键行走的情况，此时再次按下之前按下的方向键可以解除行走。
在经过测试后，与输入法和系统设置无关，只有开启GIS的时候才会出现这个问题，未开启GIS时一切正常

**Comment by phonowell** [comment]
已确认问题，定位一下之后

**Comment by phonowell** [comment]
已修复
