### ISSUE TITLE
Tactics and Party Scan Won't Work

### ISSUE THREAD

**Issue by Ozakinn** [phonowell/genshin-impact-script#152]
Hi, i'm on Asia Server.

Auto pickup, auto skip, and auto fish works well. However, I cant use tactics for some reason. I've long pressed the left click button and create a config in "characters.ini" which contains

```
[all]
on-long-press = a, e
```

which supposedly do normal attack and then E skill. But it doesn't work on me.
Party scan also doesn't work. It says "currently unable to use party scanning".

my resolution seems correct 1600x900 and rebind Switch Walk/Run to Right Ctrl.
The only thing that I did not find or do is this 
"_For East Asia players, make sure the input method is in English_"
is it in the config.ini? cant find it.
I maybe missing something important.

**Comment by phonowell** [comment]
Check if you are in a multiple game
Some features are not available then

If you don't use Chinese or Japanese, usually the input method won't bother you. Because you don't need an extra interface to type characters/kanji

**Comment by Ozakinn** [comment]
Genshin Impact, GIS, some browsers, and discord is running.
I just tried it, for some reason tactics doesnt work.
i have this in my characters.ini

```
[all]
on-long-press = a, e

[amber]
on-long-press = a~, 150
```

I just started playing genshin which recently obtained lisa as the fourth member.

**Comment by phonowell** [comment]
Hahaha looks like there seems to be a bit of translation-induced misunderstanding among us
I mean, are you playing with your friends?

In multiplayer mode, party scanning is automatically disabled

**Comment by Ozakinn** [comment]
I am playing solo. I haven't reach a level which has a multiplayer (level16).

**Comment by phonowell** [comment]
If you are a new player, then I guess the problem may be gadgets
The script relies on the status of the gadgets to make some scene judgments, and you probably don't have any yet
Once you have acquired and equipped these gadgets, the problem should be solved
