### ISSUE TITLE
扫描小队的作用？，~元素战技按了~没反应（切换了英文输入），改良跳跃的作用？  以上几个似乎没找到docs

### ISSUE THREAD

**Issue by DancingLeaf123** [phonowell/genshin-impact-script#153]

**Comment by Ice-wilderness** [comment]
一般在切换队伍的时候会扫描小队自动扫描队伍成员，以匹配不同角色的元素战技时间记录以及自定义动作，有时候自动扫描没有生效，就可以手动F12扫描。第二个我也不太清楚。改良跳跃是高度足够的时候自动打开风之翼

**Comment by phonowell** [comment]
~键删除了，版本更新中有讲
改良跳跃的另一个作用是当角色被冰冻时，会自动跳跃挣脱
