### ISSUE TITLE
软件退出导致原神无法播放声音

### ISSUE THREAD

**Issue by LiZeC123** [phonowell/genshin-impact-script#154]
程序似乎有某种BUG, 导致程序退出以后, 回到原神界面就变成静音状态. 是否是因为直接从任务栏关闭程序的时候没有做相应的处理?

**Comment by phonowell** [comment]
脚本没有驻留，界面外关闭就不能再将音量恢复了
你可以去音量合成器里再手动把声音打开

**Comment by LiZeC123** [comment]
@phonowell 但是这样操作有点不符合软件使用逻辑啊. 我当时第一反应就是遇到BUG了. 可不可以让程序从任务栏退出的时候做一下检查呢? 对于我们这种熟悉软件开发的还好说, 要是小白用户遇到这问题岂不是要搞的他们重装系统了.

或者简单一点, 在文档里面加个说明吧, 如果有需要, 我可以帮你弄个PR, 在文档里面更新一下这个注意点.

**Comment by phonowell** [comment]
> 

短期内没有更改的计划
这个免费项目的主要用户是我自己，所以不影响我个人使用的问题，只要性质不是特别恶劣都会后置到我比较有空的时间再修复

而对于所谓的小白用户，就我个人而言，希望少一点比较好
一来少一点去米哈游冲塔的人
二来之前也已经被某些爷新气过，短期内不打算再在这方面受气了
