### ISSUE TITLE
0.0.47 not set to the latest release

### ISSUE THREAD

**Issue by Lutra-Fs** [phonowell/genshin-impact-script#156]

**Comment by phonowell** [comment]
具体来说是什么问题呢？

**Comment by Lutra-Fs** [comment]
![Screenshot_20221116-025317.png](https://user-images.githubusercontent.com/36790218/201965063-975574eb-fad5-47f9-889f-b2ea94e2fe70.png) 我现在更新脚本是 detect latest release 的 现在 last release 不是 latest release

**Comment by phonowell** [comment]
还真是，发布的时候忘记勾选latest了
已修改哈
