### ISSUE TITLE
auto forward bug

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#157]
使用 auto forward 之后， @m or !@m 会因为 
https://github.com/phonowell/genshin-impact-script/blob/dc12528cd54c71dff84ffa722ecd0291431dbf05/source/movement.coffee#L117
这个咬住

无法正常执行 tactic 里的 @m or !@m

**Comment by phonowell** [comment]
这周比较忙，得等到周末才能定位了

**Comment by phonowell** [comment]
v48中应该已经解决了。
