### ISSUE TITLE
Auto fishing not work with green progress bar

### ISSUE THREAD

**Issue by abubaca4** [phonowell/genshin-impact-script#159]
For me when progress bar is green script just hold all time. Work good in other situation. In chasm point with Bitter Pufferfish.
![202537186-5d9b5078-a481-4f42-b3b9-eceffb295391_edit_40532501675584](https://user-images.githubusercontent.com/55701175/202848954-462c0a9c-3eca-4336-96ea-b94ff187d44f.png)

**Comment by phonowell** [comment]
It looks like a problem caused by the fish line stabilizer(Стабилизатор лески)
I still don't have access to this item myself, I'll try to confirm it later

**Comment by abubaca4** [comment]
> It looks like a problem caused by the fish line stabilizer(Стабилизатор лески) I still don't have access to this item myself, I'll try to confirm it later

In other locations I don't have this problem with stabilizer. Also in other point of chasm I don't have problem with stabilizer. I will test this location without stabilizer later. Mayby several factors like collor of progress bar, collor of backgroud and stabilizer broke detection of progress or good zone. I don't have problem with green progress bar in other location.

**Comment by abubaca4** [comment]
I tested with other camera rotation no problem doesn't matter stabilizer enabled or not. Problem only when green plant near left side of progress bar.

**Comment by phonowell** [comment]
Thanks for reporting this issue. I will try to fix it as soon as possible, but currently I am quite busy with other tasks. It may take up to a month or even longer to fix this problem. Thank you for your patience and feedback.

Спасибо за сообщение об этой проблеме. Я постараюсь исправить ее как можно скорее, но в настоящее время у меня много других задач. Это может занять до месяца или даже дольше. Спасибо за терпение и обратную связь.
