### ISSUE TITLE
1. 长按左键进入自动模式能自动切换角色嘛？ 

### ISSUE THREAD

**Issue by DancingLeaf123** [phonowell/genshin-impact-script#162]

**Comment by DancingLeaf123** [comment]
![image](https://user-images.githubusercontent.com/23498471/205473240-be4b5269-9118-4eb0-8592-daaf546c012d.png)
 我an找如图设置了，长按左键如何实现，每个角色打完一组切到下一个角色呢？

**Comment by phonowell** [comment]
理论上似乎可以通过写原生按键来实现该功能

但似乎有些过于无脑了，并不是很建议
