### ISSUE TITLE
全屏状态下1080p无法识别宵宫

### ISSUE THREAD

**Issue by pangpangdeduola** [phonowell/genshin-impact-script#168]
全屏状态下无法识别,在窗口模式的时候正常
![截图](https://user-images.githubusercontent.com/50541172/205494268-95ec6857-a0cf-4ab0-b444-327a25071d97.png)

**Comment by phonowell** [comment]
下版本修复

**Comment by phonowell** [comment]
经过实际测试，v48中应该已经正常了。
