### ISSUE TITLE
Left/Right/Up/Down keys binding to 'move camera' problem

### ISSUE THREAD

**Issue by oicsenoics** [phonowell/genshin-impact-script#169]
I'm using the Left/Right/Up/Down for moving instead of WASD - since 24 years until now. With the script it's still possible to move, but the camera is moving as well. It keeps going upward when walking forward constantly for example. How can I deactivate or change the key binding for 'camera movement'? The in-game menues do not allow any rebind or deactivation at all...

**Comment by phonowell** [comment]
Hi there! I'm sorry to hear that you're having trouble with the script. Unfortunately, the script is currently only set up to work with the default key bindings for the game. However, you should be able to change your keyboard mappings using a third-party tool or software. I know it's not the same, but it might be a decent workaround for you. Sorry I couldn't be more help right now!

**Comment by oicsenoics** [comment]
Hey, definitely thanks for the quick reply. I have less of a problem with the script, it's magical. And without your script, I now consider the game to be mostly unplayable. Unfortunately, I'm far too clueless to help myself. Thought of a one-liner in the config.ini or repacking the *.exe in a modified form - but have no idea about such things. Therefore, your answer really helps me, because only then do I have a targeted solution. So please don't get discouraged and keep creating such works!

**Comment by phonowell** [comment]
Thanks for the kind words! I'm glad you find the script useful. I'll continue to work on it and improve it as much as I can.

**Comment by oicsenoics** [comment]
SOLVED - switched to WASD buttons after 24 years, so the script works fine for me as well. But my left hand hurts and I repeatedly press elemental or ultimative burst instead of forward 😅
