### ISSUE TITLE
f 启用快速拾取 bug

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#17]
常常 f 键会咬住，释放不全
导致在开地图、对话，一直连发
在 2/8 之前的版本不会这样
我是海外的玩家
再麻烦帮忙看一下

**Comment by phonowell** [comment]
首先使用版本是否是最新版本？
然后确认一下f键是否有绑定其他功能，或系统是否开启了粘滞
最后，f键的功能其实是“在按下后快速点击f并向下滚动滚轮”，这个操作是否和你的某些自定义操作冲突？

**Comment by jasonliaotw** [comment]
0.0.8 已经解决
