### ISSUE TITLE
未启动脚本时，使用启动器启动游戏，声音失效是什么原因

### ISSUE THREAD

**Issue by w1501066095** [phonowell/genshin-impact-script#182]
未启动脚本时，使用启动器启动游戏，声音失效是什么原因，电脑播放音乐声音正常，游戏要有声音必须开脚本才有，这是什么原因呢？希望解答一下，谢谢

**Comment by Yabaopa** [comment]
您好 我暂时没有遇到这个情况请您具体描述一下可以吗？

**Comment by w1501066095** [comment]
就是，我使用脚本启动游戏后，此时整个游戏声音是正常的，但是当我关闭或退出脚本后或者正常使用启动器启动游戏，游戏声音就失效了，情况就是这样

**Comment by EternisField** [comment]
实测把脚本的SuspendHtokeys的勾去掉就恢复正常了

**Comment by w1501066095** [comment]
> 实测把脚本的SuspendHtokeys的勾去掉就恢复正常了

OK，我刚才试了一下，恢复了，谢谢(*^_^*)

**Comment by Xarth-Mai** [comment]
win加g 界面可以看到原神被静音了

**Comment by DerekWongJC** [comment]
config.ini里
use-mute-when-idle = 0
