### ISSUE TITLE
啟動時提示有新版本是否更新

### ISSUE THREAD

**Issue by MrLuke1110** [phonowell/genshin-impact-script#183]
已經是V47的版本，沒有新的版本，但是執行時又一直提示，請問如何更新??
![image](https://user-images.githubusercontent.com/66194793/218303972-7e0914da-1fdc-4c6c-8253-52a79e8eb772.png)

**Comment by DarkAssassin48** [comment]
+

**Comment by Mshenchen** [comment]
分支有V48的测试版本，估计正在测试接入导致的提示吧
