### ISSUE TITLE
敲碗求更新

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#186]
已经三个月未更新了，敲碗求群主更新了…

若之后无意更新，是否可以释出头像识别模组
小弟也可以协助更新头像，造福群友

**Comment by phonowell** [comment]
在写了在写了（
v48分支其实一直有在更，只是最近真的很忙
互联网寒冬体谅一下，不太好过

**Comment by phonowell** [comment]
哎呀呀stable diffusion真好玩

**Comment by phonowell** [comment]
新版本以上
