### ISSUE TITLE
shift闪避问题

### ISSUE THREAD

**Issue by jovensun** [phonowell/genshin-impact-script#187]
作者你好。
版本：0.0.47
1. shift+方向键，进入奔跑后，再按不同的方向键会触发闪避（大概率触发）。
2. shift+w，进入奔跑后，不断按a/d，会触发闪避。
3. shitf+方向键，进入奔跑后，松开方向键后会触发闪避。
4. 使用鼠标右键闪避，无上述问题。

类似的问题：
#151

**Comment by phonowell** [comment]
新版本中应当已修复该问题
