### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by satancurls** [phonowell/genshin-impact-script#19]
### Hello! 👻
I have two new suggestions!

1. _Qiqi's default combo is to prioritize charged attack (you usually want to spam charged attack for most damage)._
2. Razor has two combos, which are these:
**Using Q**
4 normal attacks and a dash to cancel the animation
**Without using Q**
3 normal attacks and a dash to cancel the animation

These two info is from the Reddit of Mains [Razor](https://www.reddit.com/r/RazorMains/) and [Qiqi](https://docs.google.com/document/d/1AlqBRGnA3MZlc_YY4qQ17K7t4ccY1YKclAG_aSwpWCE/edit#) (:

**Comment by phonowell** [comment]
Qiqi has gotten her new tactic in the new version
But because melee attacks in hitting the enemy's body or shield will have a fairly long pause in game, which leads to the script is difficult to determine the exact timing of the jump, so Razor is afraid to wait a while
