### ISSUE TITLE
When will there be an update??

### ISSUE THREAD

**Issue by DarkAssassin48** [phonowell/genshin-impact-script#199]
When will there be an update??

**Comment by DarkAssassin48** [comment]
https://github.com/phonowell/genshin-impact-script/releases/tag/0.0.48

**Comment by phonowell** [comment]
As luck would have it, I have just released an update.

**Comment by DarkAssassin48** [comment]
> 

Yes, I wrote and after 30 seconds it came out and I immediately closed it and left a link
