### ISSUE TITLE
可以新增一个凝光的轻击终极循环吗

### ISSUE THREAD

**Issue by zengrixi** [phonowell/genshin-impact-script#2]
你好！
你的脚本对我的帮助特别大，我本人也对ahk产生了不小的兴趣，正在着手学习中。
想问问你凝光的轻击重击循环如何实现？

**Comment by phonowell** [comment]
因为我本人没有用凝光，所以并不是很清楚其输出循环
如果可能的话，麻烦给出她的循环时间表，我可以告诉你如何写

**Comment by phonowell** [comment]
> 你好！
> 你的脚本对我的帮助特别大，我本人也对ahk产生了不小的兴趣，正在着手学习中。
> 想问问你凝光的轻击重击循环如何实现？

因为我本人没有用凝光，所以并不是很清楚其输出循环
如果可能的话，麻烦给出她的循环时间表，我可以告诉你如何写
