### ISSUE TITLE
琴和凝光无法识别

### ISSUE THREAD

**Issue by Hitori940101** [phonowell/genshin-impact-script#20]
凝光和琴的时候不知道为什么不识别
![D47YRN{HKS{KMDE}E)XBKPN](https://user-images.githubusercontent.com/30298918/111606942-bdcc3e00-8812-11eb-975b-f97ffe64fc50.png)
![S_DC(3N7IA_ ZCR_DKLF)U7](https://user-images.githubusercontent.com/30298918/111607145-f1a76380-8812-11eb-9a84-90c7e44d5067.png)
换位置也一样
![GVRM_8J C}UZ3I($(S@8QJ1](https://user-images.githubusercontent.com/30298918/111607425-30d5b480-8813-11eb-9f50-6f59d3aa73a9.png)

**Comment by phonowell** [comment]
更新至0.0.9即可
