### ISSUE TITLE
新版本三击W问题

### ISSUE THREAD

**Issue by xiaomohen2023** [phonowell/genshin-impact-script#203]
之前好像三击W自动前进还能用，更新后现在没反应了，有遇到这问题的人吗？
还有角色左边的标签可以关闭吗？找不到在哪里关...

**Comment by xiaomohen2023** [comment]
谢谢大佬回复，还以为是之前的快捷键呢...
还有个小问题，是关于游戏音量的，用脚本进游戏时，会把电脑音量调大，我返回桌面调节有不管用，切回游戏音量还是很大。用的EarTrumpet软件，不知道有没有关系.

**Comment by phonowell** [comment]
目前没有看到其他人反馈这个问题过
会不会是因为你的系统音量设置很高，平时只是把音量合成器中的游戏设置在比较低的音量所导致的？
