### ISSUE TITLE
Fishing mode isnt working ?

### ISSUE THREAD

**Issue by adrardossa** [phonowell/genshin-impact-script#207]
i tried pressing F11, but it doesnt do anything.. but other functions work properly

is it known issue?

**Comment by phonowell** [comment]
You need to press `F11` in the casting state, it will not work in other interfaces

**Comment by adrardossa** [comment]
yes i did, i tried on casting state 

i went back on v0.47, i tried both on casting and non casting state, its working fine.. if its not on casting state, they just do normal attack repeatedly

**Comment by adrardossa** [comment]
re-extract the zip seems solved the problem, thanks
