### ISSUE TITLE
会自己不停的按z,使用小道具

### ISSUE THREAD

**Issue by biubiustar** [phonowell/genshin-impact-script#209]

**Comment by biubiustar** [comment]
已经自己解决了，:)

**Comment by 2315506431** [comment]
既然自行解决了，为何不自行把这条iss关闭

**Comment by xueshanqiu** [comment]
我也出现这个问题来，怎么解决啊？

**Comment by biubiustar** [comment]
打开config.ini把其中的改为
use-auto-gadget = 0

**Comment by biubiustar** [comment]
> 既然自行解决了，为何不自行把这条iss关闭

不好意思，不太懂这些＞﹏＜

**Comment by biubiustar** [comment]
> 我也出现这个问题来，怎么解决啊？
打开config.ini把其中的改为
use-auto-gadget = 0
