### ISSUE TITLE
[需求] 菲谢尔攻击模式

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#21]
普攻前2下射速很快，后3箭的后摇非常严重，一般通过RR连点打断
LButton LButton R R 
依此循环

**Comment by phonowell** [comment]
更新到0.0.9即可

**Comment by jasonliaotw** [comment]
没法开启
话说 type-cb 配置后，怎么使用? 
且 type-apr 很多角色切换时只能尔而会发动
简易计时也都失准
会是因为国际服的关系吗?
再麻烦帮忙看一下，谢谢

**Comment by phonowell** [comment]
- 配置项是`type-cbt`而不是`type-cb`
- 开始使用前需要按一次`F12`来识别小队成员，否则多数功能无法生效
- 因为队员识别依赖取色，因此目前有如下限制：
  - 分辨率应当为`16:9`
  - 不能使用外挂画面滤镜

**Comment by jasonliaotw** [comment]
有了， 16:9 的分辨率是关键
不过目前测试 菲谢尔 循环输出不顺
rr 后，只有一次 LButton

**Comment by phonowell** [comment]
更新到新版本看看？

**Comment by jasonliaotw** [comment]
可行，不过发现一个问题，我看了源码后
建议一件事，弓箭的 NormalAttack delay 200 的话，攻速不够快
建议是不是要做独立 function

r r 的 delay ，建议修改成 50

自己在修改的过程，有尝试改成三段攻击再用rr取消后摇，
但 tactic.count 就来到了 11 ，12做 aim
这个有赖大佬看一下

**Comment by phonowell** [comment]
这一块的代码当初写的时候没有怎么过脑子
并没有抽象好，之后会做重构，那时候瞅瞅 0.0

**Comment by phonowell** [comment]
更新至新版即可
不过有一点需要注意，脚本不支持两次操作间隔小于`100ms`
因为这不是“安全的”操作……
