### ISSUE TITLE
关于“快速跳过对话”与“自动钓鱼”的改进建议

### ISSUE THREAD

**Issue by LuYaao** [phonowell/genshin-impact-script#212]
### 首先说一下问题：
1）**快速跳过对话**是脚本自动开启的，无法自行决定是否快速跳过（我这边是这样的，进入对话则直接快速进行）；
因此需要在开启游戏前做决定，是快速跳过对话拿到任务奖励（脚本开启），还是要好好得体验整个任务流程（正常开启）。
2）**自动钓鱼**的功能相当僵硬：需要`人工`选择一个钓鱼点，`人工`观察钓鱼点的鱼类，`人工`选择合适的鱼饵，脚本`自动`钓鱼，`人工`决定是否更换鱼饵（对应鱼类已钓完）乃至更换钓鱼点（所有鱼类已钓完）。
可见人工工作相当多；虽说实现了“自动钓鱼”，但目前来看，“部分地自动化”不仅没有将玩家从钓鱼工作中解放出来，还使得玩家在钓鱼的参与感降低，仅剩下最无趣繁琐的流程部分；故目前自动钓鱼功能相当不成熟。
### 然后说一下我的情况：
使用脚本大概有四五天了；
对脚本功能的理解还比较肤浅；
如果有我没有注意到的点或者我对该脚本的误解，请指出。
### FINAL
我仅提出上述问题作为参考，后续是否做出改变由脚本的作者决定；
希望本项目能越来越好；
希望能得到作者的回复。

**Comment by LuYaao** [comment]
### 关于“自动跳过对话”的问题补充：
**快速跳过对话**的强制性在部分场景下还会带来比较差的游戏体验；
比如`在尘歌壶与阿圆对话`场景下，脚本会自动选择`信任等阶`选项；
若玩家需要选择其他选项如`洞天百宝`，或者需要选择`再见`选项以退出对话，则必须以比脚本自动选择`信任等阶`选项更快的速度选择玩家自己想要的选项；
这种体验不是很好；
如果能提供“是否开启自动跳过对话”功能的按键就完美了；
如果已有此按键存在，而我没有发现，请指出。

**Comment by dextersa** [comment]
在0.47及以前版本，使用alt+f开启与关闭，新版本应当依然适用

**Comment by dextersa** [comment]
它和自动拾取是一套按键
