### ISSUE TITLE
Xiangling icon no longer recognized after presing F12

### ISSUE THREAD

**Issue by Qulox** [phonowell/genshin-impact-script#22]
Due to icons changes in update 1.4 some characters icons are no longer recognized. Xianling no longer has her headband and other characters updated their icons too. (Playing Global version with English language with script version 0.0.8 release) 

P.S: Sorry for english language.

**Comment by phonowell** [comment]
Update to 0.0.9 will fix it
And, don't care about the language :)

**Comment by Qulox** [comment]
Thank you.
