### ISSUE TITLE
The script doesn't work

### ISSUE THREAD

**Issue by llolipop25611** [phonowell/genshin-impact-script#23]
I did everything according to the instructions, the resolution is 16:9 but it does not work for me.

**Comment by phonowell** [comment]
Do all functions not work, or only some of them do not work?

**Comment by llolipop25611** [comment]
Nothing works, that is, the script is running but nothing happens

**Comment by jasonliaotw** [comment]
Try to edit the config.ini, 
`process = GenshinImpact.exe`
