### ISSUE TITLE
Movement keys got stucked

### ISSUE THREAD

**Issue by peterintelli** [phonowell/genshin-impact-script#24]
So when i use the script, i'm occasionally having the movement key stucked even though i turn off sprint and jump settings. Do you have any idea why?
I only use skill timer and elemental vision. it seems only me having this issue.
Thanks in advance.

**Comment by phonowell** [comment]
I think I found the reason: you probably use `shift` for sprinting, while I and most other people use the `right mouse button`
The key combinations involving `alt`, `ctrl` and `shift` are all a bit hard to get right in `ahk`, and there probably won't be a good solution anytime soon

**Comment by peterintelli** [comment]
Thanks for the answers, i think i gonna switch to RMB for sprinting
