### ISSUE TITLE
启用快速拾取 bug

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#25]
持续压按一段时间后
50% 机率会触发 Click (攻击)
且不能拾取

**Comment by phonowell** [comment]
是不是在地图边缘？
地图边缘那个深红色蒙版会影响很多取色相关的功能

**Comment by jasonliaotw** [comment]
不是…

**Comment by phonowell** [comment]
那么是稳定复现么？

**Comment by jasonliaotw** [comment]
大概抓到问题了，是屏幕解析跟游戏解析不同造成的…
不过以自行修改时间间隔后，快速拾取  0.0.9 版是最有感的快
我修改的是 genshin_78 与 genshin_79 里的时间，调整为 50 (ms)
![image](https://user-images.githubusercontent.com/34159592/113487753-6acdd880-94ec-11eb-98d6-28e597f3cc9c.png)
