### ISSUE TITLE
Mouse Movement

### ISSUE THREAD

**Issue by cFleezer** [phonowell/genshin-impact-script#26]
Hey
For some reason it wont record or play my mouse movement with F10/F11. It record the E / Q  and the W A S D but my mouse movement dont work. If you know how to fix this please let me know. 

Thank You

**Comment by phonowell** [comment]
Unfortunately the recording function for mouse is still not feasible right now
I'll try to do this later, but I'm afraid it will be too low precision to use
Unlike keyboard events, mouse movement is fast and complex, making it very difficult to record :(
