### ISSUE TITLE
增加脚本独立开关

### ISSUE THREAD

**Issue by yimo0908** [phonowell/genshin-impact-script#3]
有些脚本对于当前来说用不到，而有些又要用，希望增加一个独立配置项用以控制每个功能的开关

**Comment by phonowell** [comment]
> 有些脚本对于当前来说用不到，而有些又要用，希望增加一个独立配置项用以控制每个功能的开关

之后会增加配置文件

**Comment by phonowell** [comment]
> > 有些脚本对于当前来说用不到，而有些又要用，希望增加一个独立配置项用以控制每个功能的开关
> 
> 之后会增加配置文件

已增加配置文件

**Comment by yisk** [comment]
你好，这个单独开关怎么用呀？  不会用哎~

**Comment by phonowell** [comment]
> 你好，这个单独开关怎么用呀？ 不会用哎~

有一个`config.ini`，里边可以配置。`0`代表关闭，`1`代表开启。
具体看一下`readme`。
