### ISSUE TITLE
元素爆发 bug

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#30]
使用 alt + 1~4 原素爆发，会变成 "行走"

**Comment by phonowell** [comment]
在设置中把行走/奔跑切换键从`左ctrl`改至`右ctrl`即可

**Comment by jasonliaotw** [comment]
在 0.0.11 还是正常的，我没看明白 差异点 在哪

**Comment by phonowell** [comment]
因为0.0.11还试图做了这个ctrl的处理
0.0.12放弃了，因为发现不管怎么搞都是治标不治本，改掉键位才是一了百了

**Comment by jasonliaotw** [comment]
看来只能这样了…
