### ISSUE TITLE
I have found a bug!⚙

### ISSUE THREAD

**Issue by satancurls** [phonowell/genshin-impact-script#31]
### Hello!~
When I set Xingqiu, Keqing or Qiqi to do a charged attack it doesn't work
I'm pretty sure I'm not doing anything wrong

What I wanted to do with Qiqi and Xingqiu is:
Tap E elemental skill + charged attack
**`A, e? a, A?`** I tried a lot of combinations

With Keqing, I wanted to do it a little different:
Tap E elemental skill + tap again + charged attack looping
**`e, e, A? A, e, e?`** I also tried several, but it doesn't work

**Comment by phonowell** [comment]
For `Qiqi` & `Xingqiu`, try `A, e` or `e, A`.
But the problem is a bit more complicated for `Keqing`: after the first use of `E` her skill has gone on cd, which will make the second one ineffective; I will add a new keyword in the next version to solve this problem (probably be `ee`)

**Comment by satancurls** [comment]
I tried it on `Qiqi` and `Xingqiu` but the charged attack doesn't work =(
I tried it with other characters too, confusing because I tried other versions and it was the same

**Comment by phonowell** [comment]
If possible, could you show me your `config.ini`?

**Comment by satancurls** [comment]
Here it is: **[config.txt](https://github.com/phonowell/genshin-impact-script/files/6311917/config.txt)**.
I changed the file to .txt because GitHub doesn't support .ini for some reason but anyway
I tested it with `Xiangling` and it still doesn't work, same with `Qiqi` e o `Xingqiu`

**Comment by satancurls** [comment]
It is important to note that the elemental ability is normally used, it is only the charged attack that does not work

**Comment by satancurls** [comment]
Sorry for closing the issue 😴

**Comment by phonowell** [comment]
Thanks for uploading the file, but I'm afraid I'll have to wait until the weekend to have time for checking this
I've been working a little too much lately and lacking sleep like a cocogoat :(

**Comment by phonowell** [comment]
@satancurls `0.0.13` is released, try it out XD
