### ISSUE TITLE
莫娜 与 其它角色识别问题

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#37]
这个问题很奇怪
莫娜在昨天刚用 0.0.14 时，是可以正常识别的
但在今天又不能识别了

一度怀疑是 夜间光线 功能影响，但其它角色正常
唯独莫娜识别不出，这点蛮困扰的

其它识别有问题的如 香菱、钟离
砂糖 尔而会变成凝光

有什么方法可以 debug 吗?

**Comment by phonowell** [comment]
游戏分辨率多少，是否全屏
另外，识别错时多数情况换个角度重试一次就好

**Comment by jasonliaotw** [comment]
1920x1080, 全屏
换了很多角度、背景…

**Comment by jasonliaotw** [comment]
后来用 1366x768视窗… 
可以正确识别…

**Comment by phonowell** [comment]
> 后来用 1366x768视窗…
> 可以正确识别…

之前版本的的全屏下坐标会有偏移，新版本中是否还有这个问题呢？

**Comment by jasonliaotw** [comment]
不知道是更新的驱动，还是调整了画面品质
现在都正常了

(  0.0.14 新版 )
