### ISSUE TITLE
Skill Timer

### ISSUE THREAD

**Issue by peterintelli** [phonowell/genshin-impact-script#4]
First of all, huge thanks to you for the script.
It has cool features, the skill timer is the one i am most interested in.
Is anyway you could make the script to track skill with mutiple characters at once? And also cooldown time input window for each character everytime you switch your team member?

**Comment by phonowell** [comment]
I will add a TRUE skill timer soon, it should be able to automatically identify the characters in the team and automatically record their respective timestamps
But because it involves image recognition, the development cycle may take a little longer

**Comment by phonowell** [comment]
Now there is a new skill timer, you can have a go with it.
