### ISSUE TITLE
将行秋识别为班尼特了

### ISSUE THREAD

**Issue by teraStars** [phonowell/genshin-impact-script#43]
我是4k分辨率显示器。
![image](https://user-images.githubusercontent.com/7426499/121745464-e8d6dd00-cb36-11eb-84bd-8fe4e5ecd495.png)

**Comment by phonowell** [comment]
爬着墙的时候不能识别的……
站定再试试

**Comment by teraStars** [comment]
> 爬着墙的时候不能识别的……
> 站定再试试

试过多次了，一直不行，不知道是不是和我4k分辨率屏幕有关，但其它角色没问题。

**Comment by teraStars** [comment]
刚才仔细测试了下，确实是4K分辨率显示器的问题。我改成2560*1440窗口或者1920*1080窗口后正常了。
虽然这个在4k下有bug，但还是厉害了，我看过这么多脚本，也就你的这个脚本，大部分功能都能自由适配4k分辨率显示器。其它都是根据分辨率写死的。
