### ISSUE TITLE
经常性出现鼠标左键粘滞的现象

### ISSUE THREAD

**Issue by teraStars** [phonowell/genshin-impact-script#44]
缺省配置，版本16，运行脚本后，按f12识别角色
然后按c进入角色界面，点天赋，在各天赋间切换时，会发现明显的鼠标粘滞，有时鼠标点一下没用，得再点一下才行，有时还粘着不动。

但如果此前不按f12识别角色，则没这个问题。
我是4k分辨率显示器，不知道和这个有没有关系。

鼠标粘滞不仅表现在这个界面，在所有需要鼠标点击的界面都有可能出现。

**Comment by phonowell** [comment]
全屏时是否有问题？

**Comment by teraStars** [comment]
> 全屏时是否有问题？

刚才仔细测试了下，确实是4K分辨率显示器的问题。我改成2560*1440窗口或者1920*1080窗口后正常了。
虽然这个在4k下有bug，但还是厉害了，我看过这么多脚本，也就你的这个脚本，大部分功能都能自由适配4k分辨率显示器。其它都是根据分辨率写死的。
