### ISSUE TITLE
Bug on version 15 and 16?

### ISSUE THREAD

**Issue by roffeewest** [phonowell/genshin-impact-script#46]
It counts the cd of only 1 character in my case, Eula, when switching to another, and pressing e counts her cd and not the character that I switched to. Everything works well on version 14 and on versions 15 and 16 there is such a bug

**Comment by roffeewest** [comment]
Sometimes it fixes and works as usual, but then again * bug * goes through and counts the CD of the first character

**Comment by phonowell** [comment]
You need to use the number key 1234 to switch characters, and not use custom keys or point with the mouse, otherwise the script will not know that you have changed them

**Comment by roffeewest** [comment]
But I am using the basic 1234 key toggle setting ... So I wrote that in version 14 everything works fine
