### ISSUE TITLE
hihi 你好 有個bug

### ISSUE THREAD

**Issue by kevin821205** [phonowell/genshin-impact-script#47]
首先 謝謝寫出那麼便利的AHK讓我們使用

現在出了時裝系統 芭芭拉 換上別的時裝時

就無法辨識人物了 供您參考

**Comment by phonowell** [comment]
> 首先 謝謝寫出那麼便利的AHK讓我們使用
> 
> 現在出了時裝系統 芭芭拉 換上別的時裝時
> 
> 就無法辨識人物了 供您參考

换时装后头像也换了导致的
等我拿到时装后就更新

**Comment by phonowell** [comment]
> 首先 謝謝寫出那麼便利的AHK讓我們使用
> 
> 現在出了時裝系統 芭芭拉 換上別的時裝時
> 
> 就無法辨識人物了 供您參考

已更

**Comment by kevin821205** [comment]
<3
