### ISSUE TITLE
战斗时人物会失控

### ISSUE THREAD

**Issue by teraStars** [phonowell/genshin-impact-script#48]
刚才用迪奥娜，温迪，甘雨，钟离，打了5盘魔偶剑鬼，4盘都出现过人物失控，比如人物不能后退，或者一个劲往左走，往前走等。但我现在还没总结出什么情况下一定会出现。就是调钟离出现上个盾，甘雨按住鼠标，边走边射。

非4k分辨率，2560x1440窗口，18版本。
这个问题上次4k分辨率，16版本打深渊时也出现过。但以为是4k分辨率问题，加上不好回放，所以没发。
这次改成非4k分辨率后，发现仍然存在，但我现在也不知道怎么才能实现一定重现。
配置如下，

[region]

; 进程名称，中国大陆地区为“YuanShen.exe”，其他地区可能为“GenshinImpact.exe”
; Process name, mainland China is "YuanShen.exe", other regions may be "GenshinImpact.exe"
process = YuanShen.exe

[feature]

; 启用改良跳跃
; Enable better jump
enableBetterJump = 0

; 启用改良冲刺
; Enable better Sprint
enableBetterSprint = 0

; 启用技能计时器
; Enable skill timer
enableEasySkillTimer = 1

; 启用快速拾取
; Enable fast pickup
enableFastPickup = 0

; 启用快速对话
; Enable quick dialog
enableQuickDialog = 0

[ganyu]
tactic = A, 150

[zhongli]
tactic = a, E
type-apr = 2

感觉前面几项应该没啥影响。前面几项设为1也是如此，zhongli那段也不影响，后面测试发现去掉zhongli的配置后仍然会出现。

**Comment by phonowell** [comment]
新版本中修复了一个可能相关的问题
等更新之后再试试看吧
