### ISSUE TITLE
一些小建议和小问题

### ISSUE THREAD

**Issue by Chocky1126** [phonowell/genshin-impact-script#5]
感谢分享  结合之前另一个玩家的分享 补全了好多功能
建议可以增加一个鼠标侧键自动行走

小问题：
切人自动放战技对于钟离 迪奥娜这种长按的有点问题
技能冷却好像没啥效果 不知道怎么使用

**Comment by phonowell** [comment]
切人时按住数字键，即可施放长按战技
计时器那个等过年有空写个精确的带hud的

**Comment by Chocky1126** [comment]
酷~~ 什么时候原神能像魔兽一样写插件就好了 DBM TMW 

不过其实都是大世界乱杀的  还是方便的小功能实用

**Comment by phonowell** [comment]
> 酷~~ 什么时候原神能像魔兽一样写插件就好了 DBM TMW
> 
> 不过其实都是大世界乱杀的 还是方便的小功能实用

搞了一个新的技能计时器，可以试用一下看看
不过目前仅支持少数角色

**Comment by Chocky1126** [comment]
可能是分辨率的原因  取色位置不对 识别不到角色

**Comment by Chocky1126** [comment]
还有一个问题是游泳的时候长按右键无法持续加速

**Comment by phonowell** [comment]
> 可能是分辨率的原因 取色位置不对 识别不到角色

我个人是1600x900窗口化下开发的，其他分辨率的适配之后有时间再搞，感觉搞起来会很有点繁琐
游泳的问题主要就是没法判断角色状态，毕竟脚本是不读取内存的

**Comment by phonowell** [comment]
游泳的问题解决了……

**Comment by Chocky1126** [comment]
额  试了下还是不行  冲一下停一下  我感觉可以加个if getcolor水BUFF图标 然后持续冲刺

**Comment by phonowell** [comment]
你是什么分辨率？

**Comment by Chocky1126** [comment]
3200*1800的  我这里有一个是这样写的if ( GetColor(1844,940)=="0xFFFFFF"  这样就可以自己取颜色和坐标了 不需要自动适配了

**Comment by phonowell** [comment]
你的分辨率太高了，我甚至测都没法测
你这个是对应指定一个点的，在其他分辨率基本必挂

**Comment by phonowell** [comment]
你的分辨率太高了，我甚至测都没法测
你这个是对应指定一个点的，在其他分辨率基本必挂

**Comment by Chocky1126** [comment]
这么写的弊端就是得手动取色  不知道AHK能不能用百分比写坐标  不同分辨率位置的比例是一样的

**Comment by phonowell** [comment]
> 这么写的弊端就是得手动取色 不知道AHK能不能用百分比写坐标 不同分辨率位置的比例是一样的

可以自己转一下，并不麻烦
我代码中就是这么干的
然而不同分辨率下的ui位置并不是完全一致的

**Comment by Chocky1126** [comment]
我看懂了 函数35  取了游泳时黄色右键的颜色  但是改了坐标还是不行  我再研究下

**Comment by phonowell** [comment]
> 我看懂了 函数35 find游泳时黄色右键的颜色 我的坐标是在w-300,h-100的范围里 但是没有效果

因为你的分辨率太高了，所以这个范围里没有能找到颜色
我更新了一版，所有坐标均采用百分比作为单位，或许能解决这个问题
如果问题解决的话，麻烦在这个issue里吼一下，我好关闭它

**Comment by Chocky1126** [comment]
可以了  酷ヽ(￣▽￣)ﾉ
