### ISSUE TITLE
识别错误

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#57]
目前已知无法正确识别的有
1. 烟绯
2. 钟离
3. 琴
4. 罗莎莉亚

分辨率 1920x1080 ，没开滤镜及夜间光线
![yanfei_jean](https://user-images.githubusercontent.com/34159592/131978090-7e53601c-88a1-4718-b937-6fd9af7bae55.png)

**Comment by phonowell** [comment]
换个方向重试也异常么？如果是的话我稍晚确认一下
钟离和琴因为我最近一直在用，都还正常的

**Comment by jasonliaotw** [comment]
我也觉得闷啊… 都转了 360度了… 还是不能正常识别，尤其烟绯是我其中一个主C

**Comment by jasonliaotw** [comment]
5. 还有莫娜

**Comment by jasonliaotw** [comment]
不晓得怎么回事，原神自己更新了资源档后，又正常了…

**Comment by jasonliaotw** [comment]
不晓得怎么回事，电脑也重启了… 
今天又识别不出来

**Comment by jasonliaotw** [comment]
现在分辨率调整成 1600x900 视窗，可以正常识别

**Comment by phonowell** [comment]
> 现在分辨率调整成 1600x900 视窗，可以正常识别

我已经定位到问题了，在我这边1280*720分辨率下存在一定情况的类似问题
应该是头像素材，在不同分辨率下临近像素合并导致取色失败所导致
你提到的几个角色我都重新匹配了取色点，应该会有所改善（在23版本上线）
但这个问题比较难根治，只能等之后再遇到再解决了
