### ISSUE TITLE
关于4k分辨率的适配问题

### ISSUE THREAD

**Issue by sky2002** [phonowell/genshin-impact-script#58]
#43 已经提过这个问题了
但是今天还是没有解决
我判断是client采用了小网格从而无法正确选取对应像素从而识别错误
不知道能否将此部分重写为依据分辨率指定位置或依据屏幕长宽比和情况计算并选取更精准的像素点位置？

**Comment by Qulox** [comment]
I have your same problem, I can only play in 1080p full-screen for character recognition to work.
Sometimes in resolutions other than 1080p in full-screen (on a 4k display) it doesn't detects all characters, but if I do it in windowed mode there is no problem.

Example: 1440p full-screen = only some recognized.
1440p windowed = all recognized

**Comment by phonowell** [comment]
推测是因为像素点选取的问题所导致的
然而，解决这个的主要障碍在于，我自己使用的显示器仅有1080p
超出这个分辨率的尺寸我都没有办法实际测试

**Comment by sky2002** [comment]
这个倒也有救
我看看1920*1080以上有多少个分辨率就行了
然后挨个截图给你然后你看看到底是由于分辨率提高引起了相对位置变化
还是说相对位置/比例没变但是选取出误差了（？
以及设置网格时可以以720p或1080p的每10、5、3像素而非500，100这种需要取整可能会产生误差的

**Comment by phonowell** [comment]
目前的网格我单纯就是按百分比划分的，宽高的1%各自作为1vw和1vh来使用
当下主要可能出现问题在于，窗口模式下会有一个不定高度的标题栏
