### ISSUE TITLE
改良冲剌 与 快速拾取 ， @e?

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#59]
您好，一直以来用你的 script 非常开心
1. 改良冲剌 很好用，希望有机会加回来 (因为体力消耗太快)
2. 快速拾取的模组，0.0.18 前的快速拾取可以透过减少间隔，可以非常快速拾取 (爽度极高) ，在 0.0.19 之后，因为架构大改，没法像之前改间隔时间，如在有 2只 螃蟹时，常常只能拾取到一只而已 
3. 在切换角色时，角色的 @e? 动作组，前2个常常被吃掉… (我还在测试中)
如: 
[yanfei]
on-long-press = @e?,a,a~,600,e,300,a~,900; @m,a,a~,900; a,100,a,100,a,50,a~,1200

4. fischl 的  @m,a, 50, a, tt; 没有以前的速度了，这个部份是不能有什么改善空间?

**Comment by phonowell** [comment]
- 改良冲刺功能移除，主要因为两个原因：玩家体力普遍满了，抠冲刺的那点体力意义不大；该功能代码复杂，深渊场景下容易卡住按键
- 19版本之后统一了脚本的触发时间，最低触发间隔为100ms。之所以这么改动单纯是出于安全考虑，低于100ms的操作完全不是人手能够做到的，如果未来秋后算账的话，这批账号也一定会被首批处理。我知道有些其他第三方软件对这点完全不管不顾，所以能够实现各种光速操作，但这个脚本会一直坚持“模拟玩家本来就能够做到的操作，仅仅省却重复工作”这个思路来编写
- 留待观察，最近时间比较少，且我并没有拉烟绯起来
- 同第二点。加特林这个东西不建议日常用，特别是艾咪。米哈游出了宵宫你不去抽，还在这里搞物理艾咪加特林，这样下去明天米哈游就要破产卖大楼了！

**Comment by Qulox** [comment]
> 19版本之后统一了脚本的触发时间，最低触发间隔为100ms。之所以这么改动单纯是出于安全考虑，低于100ms的操作完全不是人手能够做到的，如果未来秋后算账的话，这批账号也一定会被首批处理。我知道有些其他第三方软件对这点完全不管不顾，所以能够实现各种光速操作，但这个脚本会一直坚持“模拟玩家本来就能够做到的操作，仅仅省却重复工作”这个思路来编写

I can get 70ms easily with little effort or even 50ms (but is very tiring for more than a few seconds).
The frequency between key-presses could be randomized a little by percentages (+/- 5% ms for example). This is used by several macro keys software to avoid detection.

**Comment by phonowell** [comment]
Good suggestion, will be added as an option in a later release.

**Comment by phonowell** [comment]
> > 19版本之后统一了脚本的触发时间，最低触发间隔为100ms。之所以这么改动单纯是出于安全考虑，低于100ms的操作完全不是人手能够做到的，如果未来秋后算账的话，这批账号也一定会被首批处理。我知道有些其他第三方软件对这点完全不管不顾，所以能够实现各种光速操作，但这个脚本会一直坚持“模拟玩家本来就能够做到的操作，仅仅省却重复工作”这个思路来编写
> 
> I can get 70ms easily with little effort or even 50ms (but is very tiring for more than a few seconds).
> The frequency between key-presses could be randomized a little by percentages (+/- 5% ms for example). This is used by several macro keys software to avoid detection.

Good suggestion, will be added as an option in a later release.
