### ISSUE TITLE
登龙剑

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#60]
目前有尝试组合登龙剑，都不能成功 (没有攻击)
看了一下应该是 j 的延时比较长，所以攻击被延迟了

这个有办法实现吗?

**Comment by phonowell** [comment]
脚本内置的跳跃前后固定有至少100ms延时，所以这个可能暂时无法做到
目前登龙似乎也只有迪卢克比较有用，感觉上不是特别具备泛用性……

**Comment by phonowell** [comment]
v28版本你可以使用新的`ja`关键字试试
但因为我并没有测试过这个关键字，所以并不确定它是否能够正常生效

**Comment by jasonliaotw** [comment]
bug: ja 后不能循环技能
另外 ja 的攻击时间，我还在找最适当的间隔时间 ，50ms 有点太短，但 190~210 又不太稳定 
(去秘境的门口，就可以测出登龙剑)

**Comment by rtj666** [comment]
现在登龙能实现吗，效果怎么样

**Comment by Kingxs840** [comment]
同求登龙斩

**Comment by DancingLeaf123** [comment]
登龙感觉靠tactic很难做到，因为位置不同的时候一刀砍到怪物身上的时间不同，而又登龙卡的就那么几帧（10几毫秒量级），所以光靠tactic实现感觉不容易，这是我这边的情况。
