### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#61]
在  0.0.22 及 0.0.23 上 (其他版本不会)
编译 npm run build 会出现下图错误
![image](https://user-images.githubusercontent.com/34159592/134572863-fdd3fbc1-9cf5-4e16-8f67-cda9d7f9a445.png)

**Comment by phonowell** [comment]
新版本的编译入口改动过
之前是typescript，但在windows下启动太慢了，所以改到了javascript
你把task下的一圈儿ts文件全编译到js就可以了
