### ISSUE TITLE
It's possible to add Q (elemental burst) to tactic module?

### ISSUE THREAD

**Issue by Qulox** [phonowell/genshin-impact-script#62]
Eula's best attack rotation is:
E > Q > N4 > Hold E > N4

`e, q, a, a, a, a, ~e, a, a, a, a`

It is possible for this to work?

**Comment by phonowell** [comment]
The `q` keyword has been added in one of the previous updates.
However, it is not well represented due to the lack of support for the feature.
You can try to use it, but it's best not to get your hopes up.
