### ISSUE TITLE
关于热键

### ISSUE THREAD

**Issue by zy321314** [phonowell/genshin-impact-script#63]
请问您是否可以更改钓鱼热键，或者单独在config.ini里添加功能开关，F11和我其他的工具有按键冲突。

**Comment by zy321314** [comment]
The original is in Chinese

**Comment by zy321314** [comment]
Can you change the fishing hotkey or add a function switch in config.ini alone? F11 conflicts with other tools.

**Comment by phonowell** [comment]
目前为止没有添加这方面功能的计划
你可以尝试更改你其他工具的热键以规避按键冲突
