### ISSUE TITLE
迪卢克的e应该直接识别为一段cd,不应该每次e连招都触发计时器

### ISSUE THREAD

**Issue by daofeng2015** [phonowell/genshin-impact-script#65]
还有神里的识别为啥只显示一下-10s,然后突然消失了,目前就发现这二个问题

**Comment by daofeng2015** [comment]
有时候行秋会直接e识别不出来(非祭礼武器)...

**Comment by phonowell** [comment]
> 还有神里的识别为啥只显示一下-10s,然后突然消失了,目前就发现这二个问题

已经确认是一个bug了，会在新版本修复
2.1版本中的神里名字变更了，从`kamisato`变更为了`kamisato ayaka`，有一处地方忘记更改才导致了这个bug
