### ISSUE TITLE
关于自动拾取/跳过对话

### ISSUE THREAD

**Issue by clcm8629** [phonowell/genshin-impact-script#66]
自动拾取好像对某些拾取物不生效，如小生物、昆虫、星螺，闪光点﹝会爆出圣遗物或者食材、矿物的闪光﹞
还有希望自动拾取跟跳过对话可以分开热键开关，自动拾取大地图探索时非常好用
但是有时候忘了关容易跳过NPC成就任务的关键选项

**Comment by phonowell** [comment]
采集选项在1600*900窗口分辨率下可用，你可以考虑切到这个分辨率先
闪光点并不打算放进自动触发序列，因为很影响捡圣遗物
另外快速跳过对话这个还是依赖自己记住比较好，感觉上并不是很有添加额外热键的必要性

**Comment by clcm8629** [comment]
解决了，去config.ini把快速事件关了就可以只留下自动拾取
