### ISSUE TITLE
还有一个小问题

### ISSUE THREAD

**Issue by hinyb** [phonowell/genshin-impact-script#7]
那个，钟离不知道为什么我长按短按的计时器都算短按的4秒QWQ

**Comment by phonowell** [comment]
手头没有电脑没法检查，推测是长按时间太短？
现在但逻辑是按住到松开的时间低于200毫秒算点按，反之长按
这个200毫秒基本是个随手写的数值，没有自己测过
之后能摸到PC的时候瞅瞅

**Comment by hinyb** [comment]
加油大佬\(@^0^@)/

**Comment by phonowell** [comment]
仔细检查了一下，发现是一个bug：角色直接使用E技能时，不能正确记录时间
已经修复了
