### ISSUE TITLE
switching between character delay or not registering

### ISSUE THREAD

**Issue by thu2468** [phonowell/genshin-impact-script#70]
When switching between character i have to press the number key again for it to detect that it is on that character.

**Comment by thu2468** [comment]
; 弱网络环境
; 0 | 1
weak-network = 0

; 性能
; When your device performance is insufficient, or the network environment is not good, please turn down this option
; 当你的设备性能不足，或网络环境较差时，请调低该选项
; high | medium | low
performance = medium

whats the difference between these two settings?
the bottom one is from the NA config and top is CN config
which one do you use?

**Comment by phonowell** [comment]
`basic/weak-network` is correct.
`basic/performance` has been deprecated.
