### ISSUE TITLE
关于 0.0.26 移除 @m 自定义动作模组

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#72]
因为有在用 可莉
on-long-press = @m,a,330,@m,a,330,@m,a,a~,10; a,a~,600
( @m 走 a 3次+ 重击 ，不移动时， a + 重击 )

我这2项 动作就会派不上用场了，再请考虑一下，谢谢。
(或者有其它替代自定义方式?)

**Comment by phonowell** [comment]
> 因为有在用 可莉 on-long-press = @m,a,330,@m,a,330,@m,a,a~,10; a,a~,600 ( @m 走 a 3次+ 重击 ，不移动时， a + 重击 )
> 
> 我这2项 动作就会派不上用场了，再请考虑一下，谢谢。 (或者有其它替代自定义方式?)

回滚了，更新即可
