### ISSUE TITLE
Hu Tao Combo Not working for N1CD or N2CD

### ISSUE THREAD

**Issue by thu2468** [phonowell/genshin-impact-script#73]
There combo for hu tao here: https://keqingmains.com/hu-tao/#Animation_Cancels_Combos

![image](https://user-images.githubusercontent.com/1341488/140033021-8f14e8d5-fdd0-43b8-a211-770bae06a068.png)
Trying to make these combo in the script doesnt work

**Comment by thu2468** [comment]
Dash doesnt cancel the charge attack

**Comment by phonowell** [comment]
What's your tactic script for her?

**Comment by thu2468** [comment]
!@e, a, e, @e, 300; a~, 150, s, 50
i tried this that was a example from tactic example. I replaced j with s for dash instead of jump
im trying tto make it so it does like what this video does. https://www.youtube.com/watch?v=GZj5E_jVPfk

**Comment by thu2468** [comment]
Doing this on-long-press = s, 150 doesnt work also

**Comment by phonowell** [comment]
This is a bug and will be fixed later in v28

**Comment by phonowell** [comment]
v28 is released right now.

**Comment by thu2468** [comment]
still doesnt work after v28
i did 
[hu_tao]
on-long-press = s
to see if sprinting works

**Comment by jasonliaotw** [comment]
found the bug, wrong function name
![image](https://user-images.githubusercontent.com/34159592/144044787-00e045f8-d570-476f-960b-08e423370f21.png)

**Comment by thu2468** [comment]
Ok when will new update be?
