### ISSUE TITLE
切换人物时会有小概率使用E技能

### ISSUE THREAD

**Issue by Vintura96** [phonowell/genshin-impact-script#75]
配置里未使用攻击模组，切换人物时不管成功或未成功，会有概率出现使用元素战技E。 
可以通过频繁快速切换人物来触发该BUG，数字键1~4 之间来回按，每个按键只按一次就能容易触发BUG，如：1、3、2、4、3、2、1、2  。
如果重复按下数字键则不会触发。如： 1、1、3、3、2、2

**Comment by phonowell** [comment]
v28版本修复

**Comment by phonowell** [comment]
已修复
