### ISSUE TITLE
计时器与武器被动冲突

### ISSUE THREAD

**Issue by madbagw** [phonowell/genshin-impact-script#8]
计时器在触发祭礼剑被动重置E技能的情况下不会重置计时，估计祭礼系的武器都有这个bug，不过这个玩意感觉不太好修吧，毕竟随机器是游戏里的

**Comment by phonowell** [comment]
祭礼武器没辙，因为在不读取内存的前提下

**Comment by madbagw** [comment]
那把这个issue给close了吧（

**Comment by madbagw** [comment]
我有个想法就是加个开关，可以手动指定哪些角色是否可以通过按E强制重置计时器

**Comment by phonowell** [comment]
> 我有个想法就是加个开关，可以手动指定哪些角色是否可以通过按E强制重置计时器

理论可行，不过角色也太多了……
