### ISSUE TITLE
请问能加入圣遗物强化的脚本功能吗

### ISSUE THREAD

**Issue by lemonchan1** [phonowell/genshin-impact-script#81]

**Comment by phonowell** [comment]
具体是指什么？

**Comment by lemonchan1** [comment]
就是圣遗物强化时通过自动点击选择圣遗物、强化、详情、强化四步来跳过强化动画以达到快速强化的目的，如果能加上背包圣遗物自动选择摧毁就更好了。其实只是很简单的操作，但是我用py写的脚本似乎没法运行，查到有说法是游戏对api调用鼠标有屏蔽，所以只能来求助大神了

**Comment by phonowell** [comment]
感觉上并不是很泛用
