### ISSUE TITLE
快速拾取物品/跳过对话失效

### ISSUE THREAD

**Issue by clcm8629** [phonowell/genshin-impact-script#82]
在config.ini文件里开启＂启用快速拾取＂然后在游戏里长按F
＂快速拾取物品/跳过对话失效＂的功能好像就失效了

**Comment by phonowell** [comment]
新版本下这两个功能互斥，在开启快速拾取时，按住F的行为是“暂停”；但此时点按不受影响
改动原因是因为开启该功能时，通常不再需要长按F

**Comment by clcm8629** [comment]
了解，因为之前“启用快速拾取”这个功能我都是常驻开启的
碰到需要捡圣遗物或抓晶蝶、生物的时候因为不能识别所以都是长按F
对话的时候如果需要跳过也是长按F不用再额外使用快捷键，觉得挺方便的。
希望作者能评估看看

**Comment by phonowell** [comment]
1600*900分辨率下快速拾取可以捕获生物，其它分辨率未适配
只要开启快速跳过对话功能，快速拾取也会自动快速跳过对话
