### ISSUE TITLE
请大神指导怎么编译

### ISSUE THREAD

**Issue by jasonliaotw** [phonowell/genshin-impact-script#86]
0.0.32 编译不过
![image](https://user-images.githubusercontent.com/34159592/155218452-99ee428e-2c10-4f17-804a-dfb557361643.png)

是不是有什么条件限制? 还是缺少了什么?
OS: win10
node: v16.13.0
npm: 8.1.0

**Comment by phonowell** [comment]
缺少了角色信息数据，这部分数据在v31版本中被分离了
你自己提供一份就可以编译了
但我并不推荐现在自行编译，有问题可以反馈

**Comment by jasonliaotw** [comment]
角色信息数据有范本吗?
可否提供参考? 谢谢大神

**Comment by phonowell** [comment]
和之前版本中的差不多；它只是因为作为静态数据不怎么改变，被移出了项目

**Comment by jasonliaotw** [comment]
好的，再次感谢大神做出这么神奇的项目
因为自己的使用习惯，会加快速拾取
加入对应的 XButton1 & 2 及其它组合键，所以会去修改 ahk 档

因为有修改的需求，自己胡弄编译出来了
 '../../gis-static/lib/Gdip_All.ahk' 
 '../../gis-static/lib/Gdip_PixelSearch.ahk' 
 '../../gis-static/lib/ShiftAppVolume.ahk'
这3个引述文档是大神自己修改过的，还是网上能找到的?

另外编译后，除了游戏非全屏可以去框边，非活动视窗静音都可正常外，主要功能都不会运作
是因为自行编译的关系吗? (有没有其它限制?)
以上再请大神指导一下，谢谢

**Comment by phonowell** [comment]
那你完全可以自己新写一个ahk写对应功能，同时启用，并不会相互影响
include的几个文件就是之前放的，后边单独从项目里抽离出来了
编译后会生成两个版本，体积较大的才是完整版

**Comment by jasonliaotw** [comment]
找到问题了，是 PixelSearch 有 x86 x64 的问题
https://www.autohotkey.com/boards/viewtopic.php?style=1&t=97650
用里面提供的 lib 就可以正常运作了，感谢大神
