### ISSUE TITLE
Identifying characters don't work on some occassion

### ISSUE THREAD

**Issue by mmn6d6d6e** [phonowell/genshin-impact-script#87]
Several combinations of character slot positions and/or whether they are selected or not makes them cannot be identified.

Here's what I found:
|Character|Slot 1|Slot 2|Slot 3|Slot 4|
|-|-|-|-|-|
|Chongyun (on-field)|✅|❌|✅|✅|
|Chongyun (off-field)|✅|❌|❌|✅|
|Keqing (on-field)|❌|✅|❌|❌|
|Keqing (off-field)|✅|✅|✅|✅|
|Diluc (on-field)|❌|❌|❌|❌|
|Diluc (off-field)|✅|❌|❌|✅|
|Sucrose (on-field)|❌|❌|❌|❌|
|Sucrose (off-field)|❌|❌|❌|❌|

Samples screenshot of identifying characters when Keqing selected vs not selected:
![image](https://user-images.githubusercontent.com/19344000/157882755-3f45e188-1def-4330-9df0-43ad5d610865.png)

**Comment by mmn6d6d6e** [comment]
Just tried v0.0.35, still the same.

Does the graphic setting affect this feature? Here is my setting. (Brightness is set to default)
![image](https://user-images.githubusercontent.com/19344000/167379010-57ca478d-dd0d-4780-abc5-384ab39c58b0.png)

I'm not using a filter or something like that.

**Comment by phonowell** [comment]
> Just tried v0.0.35, still the same.
> 
> Does the graphic setting affect this feature? Here is my setting. (Brightness is set to default) ![image](https://user-images.githubusercontent.com/19344000/167379010-57ca478d-dd0d-4780-abc5-384ab39c58b0.png)
> 
> I'm not using a filter or something like that.

Aha, your resolution may be too low, switch to a resolution of 1600 * 900 or more try it

**Comment by mmn6d6d6e** [comment]
I see.

Unfortunately, I can't try this.
1366 x 768 is the highest resolution I can set. 1600 x 900 doesn't even show up as an option.

And I just found out that the minimum resolution is mentioned on docs, so it's my fault for not realizing this.

Thx for the clarification.
