### ISSUE TITLE
[Request] Add auto perfect cooking? is that possible?

### ISSUE THREAD

**Issue by EchoesFromBeyond** [phonowell/genshin-impact-script#90]
I have a disability with my hands and it's very hard to get that auto perfect cooking. Would you be willing to add that as a feature? Thank you so much for this tool, it truly helps me.

**Comment by phonowell** [comment]
I had considered this feature, but it didn't feel like very reusable.
But the good news is that the new version adds a recording feature to fulfill this request.

**Comment by HotdogMassacre** [comment]
This is awesome, thank you! Is there a way though to turn off the Beeps @phonowell
