### ISSUE TITLE
Not working with the new update

### ISSUE THREAD

**Issue by iamsunwei** [phonowell/genshin-impact-script#91]
New update kills most features. F11 doesn't activate fishing, holding F doesn't skip dialogue, etc.

**Comment by iamsunwei** [comment]
Old 0.0.31 still works, but 0.0.32 doesn't work with Genshin Impact Global

**Comment by HotdogMassacre** [comment]
@iamsunwei I think you likely have a filter on or something as it's still working just fine.

**Comment by iamsunwei** [comment]
> @iamsunwei I think you likely have a filter on or something as it's still working just fine.

Definitely not the case. I don't have or use any filters and also none of the hotkeys even work. The only thing that works is that the music mutes when you're alt-tabbed. Everything else in 0.0.32 is nonfunctional.

**Comment by HotdogMassacre** [comment]
The script works by PixelScanning, so if you have something that is potentially changing your colors it wont work. Do you have HDR on, if so that would also do it.

**Comment by iamsunwei** [comment]
Like I said, it has nothing to do with improper detection. The hotkeys simply _do not respond_ . Hitting F11 doesn't activate fishing mode, holding F doesn't skip dialogue, and yes, all of the settings are active.

**Comment by HotdogMassacre** [comment]
good luck then.

**Comment by phonowell** [comment]
Maybe you started `giss.exe` instead of `gis.exe`? The former is just a simplified version of the latter and does not contain most of the functions.

**Comment by iamsunwei** [comment]
my bad i did have giss
