### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by xidecca** [phonowell/genshin-impact-script#95]
Hello, I'm so sorry if this is a dumb question, but I am so clueless to how this script works? is there a manual that I can follow on how to actually use this? do I just run the .exe and start using the hotkeys?

**Comment by HotdogMassacre** [comment]
@xidecca This is not the appropriate place to post questions, this is an issue board for bug reports / feature requests. Please look at the Readme that's on the GitHub post, it has a manual and tells you how to use it, and ask the questions in the Discussions section.
