### ISSUE TITLE
Version 0.0.34 detected as a trojan

### ISSUE THREAD

**Issue by Qulox** [phonowell/genshin-impact-script#96]
https://www.virustotal.com/gui/file/ab41ef9c7701dfc9ecc7389ea31ed1aa4b4b5f728e8d32d05efa3552f1dc333b/detection

Detected as `Trojan:Win32/Sabsik.FL.B!ml` on Virustotal's Microsoft Defender and other 4 antivirus (though really bad ones) and as `Trojan:Win32/Wacatac.B!ml` on my PC's Defender.

Most likely a false positive but I should let you know.

**Comment by Qulox** [comment]
Only GIS.exe is detected, GISS.exe has no problem.

**Comment by HotdogMassacre** [comment]
This is pretty common with items that do things like automation, hacks, trainers, etc. The crappier virus scanners don't do a great job at the heuristics and will frequently say something is bad just because it saw a call that is usually done commonly in malware.
