### ISSUE TITLE
[Request] Add a PAUSE key

### ISSUE THREAD

**Issue by HotdogMassacre** [phonowell/genshin-impact-script#97]
Feature Request, Please add a PAUSE key so that we can halt the functionality of GIS without killing it. I run my own AutoHotkey scripts, and when yours is running it takes over some of the keys mine does differently. Would love to see a PAUSE button we can have that will do a Pause Script.

**Comment by phonowell** [comment]
Currently there are some difficulties to make this feature work, `Coffee-AHK`, although based on `AHK`, has added some extra mechanisms inside to simulate a javascript-like runtime environment, which makes it impossible to simply implement it via hotkeys. Currently you can right-click on the taskbar icon to suspend or resume the script, I will further improve the library to implement this feature later.
